version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2-node
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "cypress_rails.gemspec" }}
          - v1-dependencies-
      - restore_cache:
          keys:
          - v1-passing-node-modules-{{ checksum "./spec/support/dummy_passing/yarn.lock" }}
          - v1-passing-node-modules-
      - restore_cache:
          keys:
          - v1-failing-node-modules-{{ checksum "./spec/support/dummy_failing/yarn.lock" }}
          - v1-failing-node-modules-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Install passing node dependencies
          command: |
            cd spec/support/dummy_passing && yarn install && npx cypress install && cd -
      - run:
          name: Install failing node dependencies
          command: |
            cd spec/support/dummy_failing && yarn install && npx cypress install && cd -
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - save_cache:
          paths:
            - ./spec/support/dummy_passing/node_modules
          key: v1-passing-node-dependencies-{{ checksum "./spec/support/dummy_passing/yarn.lock" }}
      - save_cache:
          paths:
            - ./spec/support/dummy_failing/node_modules
          key: v1-failing-node-dependencies-{{ checksum "./spec/support/dummy_failing/yarn.lock" }}
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
